[build-system]
requires = ["hatchling>=1.17.0"]
build-backend = "hatchling.build"

[project]
name = "aise"
version = "0.1.0"
description = "Bridging research problems of the fields AI safety and AI ethics"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bertopic>=0.17.3",
    "nltk>=3.9.2",
    "pandas>=2.3.2",
    "pip>=25.2",
    "pydot>=4.0.1",
    "seaborn>=0.13.2",
    "spacy>=3.8.7",
    "typer>=0.19.2",
]

[project.scripts]
aise = "aise.analysis:cli"

[tool.ruff]
line-length = 90
target-version = "py311"
select = [
    "ALL",
]
ignore = [
    "ANN",
    "COM",
    "C90",
    "DJ",
    "EXE",
    "T10",
    "TID",
    "FBT",
    "T201",
    "S603",
    "N806",
    "N803",
    "PLR0913",
    "PLR0912",
    "PLR0915",
    "B008",
]
